version: "3"

services:
  db:
    container_name: pim_postgres
    image: postgres
    restart: always
    ports:
      - 3030:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    container_name: pim_adminer
    image: adminer
    restart: always
    ports:
      - 9080:8080

volumes:
  my-datavolume: