# Generated by Django 3.1.1 on 2020-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0007_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
