# Generated by Django 3.1.1 on 2020-09-03 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pim', '0008_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.UUIDField(default=uuid.UUID('8d8560f4-6bd1-4882-86b0-aba9ed25f0b3'), editable=False)),
                ('ean', models.UUIDField(default=uuid.UUID('19ef74ac-c876-475e-805a-6717b12b4169'), editable=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoryRelationship', to='pim.category')),
            ],
        ),
    ]
