# Generated by Django 3.1.1 on 2020-09-03 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200903_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isDeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('930ca4a7-5973-464d-859f-212323307eb6'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('33ff01f3-f317-4d92-a1e9-7c1e8114803c'), editable=False),
        ),
    ]
