# Generated by Django 3.1.1 on 2020-09-03 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200903_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('3f221644-cced-446e-8993-45e28cce4781'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('74221083-34f3-4d35-8299-de9540b81807'), editable=False),
        ),
    ]
