# Generated by Django 3.1.1 on 2020-09-03 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0008_delete_article'),
        ('article', '0006_auto_20200903_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='pim.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('8d24f247-4677-462f-ab9c-9c53dc706a01'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('8192cbd2-1a8e-4d33-861b-086868a09901'), editable=False),
        ),
    ]
