# Generated by Django 3.1.1 on 2020-09-03 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200903_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('6be7e1bd-3ab0-4f46-8601-3e36360e4eb3'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('faffb6d7-8740-475a-8b88-7e79c2321965'), editable=False),
        ),
    ]
