# Generated by Django 3.1.1 on 2020-09-03 20:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200903_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('8dd22233-a78e-4b32-b16e-080517334fc8'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('c739c1d4-7df7-4a32-8ee4-547fbe3fb671'), editable=False),
        ),
    ]
