# Generated by Django 3.1.1 on 2020-09-03 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200903_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('bf36a772-e5f8-4dcd-a522-c340705d8299'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('d9131cb8-da1e-41cc-aa58-f1afeb518dcd'), editable=False),
        ),
    ]
