# Generated by Django 3.1.1 on 2020-09-03 21:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0008_delete_article'),
        ('article', '0012_auto_20200903_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='pim.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.UUIDField(default=uuid.UUID('cf7b49ed-8170-406f-992d-5def95334472'), editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='sku',
            field=models.UUIDField(default=uuid.UUID('cf89474c-c1b6-4be2-b324-e1a807f873b8'), editable=False),
        ),
    ]
